import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const read=p=>readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
test('Amy FX public source uses permanent production identity',()=>{const g=read('app/build.gradle.kts'),v=read('app/src/main/assets/app-version.js');assert.match(g,/configuredApplicationId = System\.getenv\("AMYFX_APPLICATION_ID"\) \?: "com\.amyelitesuite"/);assert.match(g,/configuredAppLabel = System\.getenv\("AMYFX_APP_LABEL"\) \?: "Amy FX"/);assert.match(g,/configuredUriScheme = System\.getenv\("AMYFX_URI_SCHEME"\) \?: "amyfx"/);assert.match(g,/versionCode[^\n]*52/);assert.match(g,/versionName[^\n]*"2\.0\.2"/);assert.match(v,/name: '2\.0\.2', code: 53/);assert.doesNotMatch(g,/learningpreview|Amy FX Preview|amyfxpreview|preview-update\.json/);assert.doesNotMatch(v,/Preview|personal\/amyfx-private/)});
test('published metadata is never ahead of published APK',()=>{const m=JSON.parse(read('update.json'));const versions=new Map([[40,'1.4.17'],[41,'1.5.0'],[42,'1.5.1'],[43,'1.5.2'],[44,'1.5.3'],[45,'1.5.4'],[46,'1.5.5'],[47,'1.5.6'],[48,'1.5.7'],[49,'1.5.8'],[50,'1.5.9'],[51,'2.0.0'],[52,'2.0.2']]);assert.equal(m.latest_version_name,versions.get(m.latest_version_code));assert.ok(m.latest_version_code<=52);assert.ok(m.release_notes.length>0)});
test('client does not persist TwelveData credentials',()=>{const main=read('app/src/main/assets/apps/mapping/js/main.js'),bridge=read('app/src/main/assets/apps/mapping/js/bridge/android-bridge.js'),native=read('app/src/main/java/com/amyelitesuite/MainActivity.kt');assert.doesNotMatch(main,/localStorage\.getItem\('twelve_api_key'\)/);assert.doesNotMatch(bridge,/localStorage\.setItem\('twelve_api_key'/);assert.match(native,/SecurePrefs\.remove\(mContext, "api_key"\)/)});
test('release workflows pin certificate and inspect v1 plus v2',()=>{const g=read('app/build.gradle.kts');assert.match(g,/enableV1Signing = true/);assert.match(g,/enableV2Signing = true/);for(const p of ['.github/workflows/build-apk.yml','.github/workflows/build-release.yml','.github/workflows/stage5-apply.yml']){const w=read(p);assert.match(w,/META-INF\/\[\^\/\]\+\\\.SF/);assert.match(w,/META-INF\/\[\^\/\]\+\\\.\(RSA\|DSA\|EC\)/);assert.match(w,/0x7109871A/);assert.match(w,/keytool -printcert/);assert.match(w,/47:C2:32:BC:44:FA:63:C9:2F:FE:41:1F:71:40:40:4C:09:AA:2A:9C:BF:82:B1:85:9A:86:0B:85:56:7B:AD:C7/)}const rolling=read('.github/workflows/build-apk.yml');assert.match(rolling,/AMYFX_VERSION_NAME: "2\.0\.2"/);assert.match(rolling,/AMYFX_VERSION_CODE: "52"/);assert.match(rolling,/Verify public update manifest source/);const manual=read('.github/workflows/build-release.yml');assert.match(manual,/default: "2\.0\.2"/);assert.match(manual,/default: "52"/);const candidate=read('.github/workflows/stage5-apply.yml');assert.match(candidate,/Validate Amy FX 2\.0\.2/)});
test('public Firebase client remains public',()=>{const f=JSON.parse(read('app/google-services.json'));assert.equal(f.client[0].client_info.android_client_info.package_name,'com.amyelitesuite');assert.equal('private_key' in f,false)});
