#!/usr/bin/env python3
"""Run the proven Preview promotion engine for the next production release."""

import json
from pathlib import Path
import sys

BASE_SCRIPT = Path(__file__).with_name("promote-preview-to-production.py")
source = BASE_SCRIPT.read_text(encoding="utf-8")
target = Path(sys.argv[2]).resolve()

# GitHub Actions cannot push commits that create or modify workflow files with
# the job token. Keep the reviewed production release workflows byte-for-byte;
# only runtime and application sources are generated by the parity pipeline.
release_workflow_paths = (
    Path(".github/workflows/build-apk.yml"),
    Path(".github/workflows/build-release.yml"),
)
preserved_release_workflows = {}
for relative in release_workflow_paths:
    path = target / relative
    if not path.exists():
        raise SystemExit(f"[latest-preview-promotion] missing production workflow: {relative}")
    preserved_release_workflows[relative] = path.read_bytes()

required_replacements = (
    ('VERSION = "2.3.0"', 'VERSION = "2.3.1"'),
    ('VERSION_CODE = 58', 'VERSION_CODE = 59'),
    ('content = read(path).replace("2.2.1", VERSION)', 'content = re.sub(r"\\b2\\.3\\.0\\b", VERSION, read(path))'),
    ('r"(?<!\\d)57(?!\\d)"', 'r"(?<!\\d)58(?!\\d)"'),
)
for old, new in required_replacements:
    if old not in source:
        raise SystemExit(f"[latest-preview-promotion] required base marker missing: {old}")
    source = source.replace(old, new)

source = source.replace("Amy FX 2.3.0", "Amy FX 2.3.1")
source = source.replace("runtime v5", "runtime v6")
source = source.replace("version: '5.0.0'", "version: '6.0.0'")

sys.argv[0] = str(BASE_SCRIPT)
namespace = {
    "__name__": "__main__",
    "__file__": str(BASE_SCRIPT),
    "__package__": None,
}
exec(compile(source, str(BASE_SCRIPT), "exec"), namespace)

for relative, content in preserved_release_workflows.items():
    path = target / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content)

manifest_path = target / "update.json"
manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
manifest.update({
    "latest_version_code": 59,
    "latest_version_name": "2.3.1",
    "versionCode": 59,
    "version": "2.3.1",
    "releaseDate": "2026-08-04",
})
notes = [
    "Engine dan runtime Amy FX produksi kini zero-drift terhadap Amy FX Preview 2.0.0-preview.310 setelah normalisasi identitas produksi.",
    "Mapping memakai closed-candle runtime v6 sehingga hasil candle terakhir tetap tampil, refresh mengikuti event candle close, dan harga live tidak merender ulang analisis.",
    "Structural bias, dependency refresh, Dashboard dan Analisis terpisah, Rencana Eksekusi, Entry Watch, serta Market Outlook mengikuti implementasi Preview terbaru.",
    "Scalper Engine, Scalper Entry Watch, execution authority, decision bridge, lifecycle, dan riwayat permanen mengikuti source Preview yang sama.",
    "Package com.amyelitesuite, URI amyfx, signing permanen, update channel main, topologi news produksi, Market Intel public gateway, dan data pengguna tetap dipertahankan."
]
manifest["release_notes"] = notes
manifest["changelog"] = notes
manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print("Updated Amy FX production update manifest to 2.3.1 (59) and preserved reviewed production release workflows.")
