-- Amy FX public promotion of Scalper Pattern v3.
-- Existing amyfx_preview_* table names are retained because the shared Scalper backend already uses them.
-- This migration intentionally excludes the Preview-only news delivery ledger and scheduler routes.

alter table public.amyfx_preview_scalper_setups drop constraint if exists amyfx_preview_scalper_setups_model_check;
alter table public.amyfx_preview_scalper_setups
  add constraint amyfx_preview_scalper_setups_model_check check (model in (
    'IFVG_SCALPER','FVG_BUY_HIGH_QUALITY',
    'FVG','CRT','ORDER_BLOCK','BREAKER_BLOCK','RETEST_BOS',
    'TRENDLINE_BREAK_RETEST','EMA_PULLBACK','FALSE_BREAKOUT','RANGE_EXPANSION','AMD'
  ));

create table if not exists public.amyfx_preview_scalper_pattern_configs (
  config_type text not null check (config_type in ('BASE','REPAIR','AMD')),
  version text not null,
  enabled boolean not null default true,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  primary key (config_type, version)
);

insert into public.amyfx_preview_scalper_pattern_configs (config_type, version, enabled, payload)
values
  ('BASE', 'BT6-2025-V1', true, '{"scope":"nine_existing_drivers","entry":"raw_detector_unchanged","tp1_points":10,"tp2_points":20,"break_even":false,"max_hold_hours":24,"same_candle_rule":"SL_FIRST"}'::jsonb),
  ('REPAIR', 'BT6.1-2026-H1-V1', true, '{"drivers":["ORDER_BLOCK","RETEST_BOS","EMA_PULLBACK","BREAKER_BLOCK"],"operation":"base_gate_and_repair_overlay"}'::jsonb),
  ('AMD', 'AMD-2025-V1', true, '{"timeframes":["M30","H1"],"entry":"FVG_MIDPOINT_LIMIT","risk_points_min":10,"risk_points_max":30,"stop_cap_points":50}'::jsonb)
on conflict (config_type, version) do nothing;

create table if not exists public.amyfx_preview_scalper_candidate_telemetry (
  id bigint generated by default as identity primary key,
  candidate_id text not null,
  engine_version text not null,
  base_config_version text not null,
  repair_config_version text not null,
  driver_id text not null,
  timeframe text not null check (timeframe in ('M15','M30','H1','H4')),
  direction text not null check (direction in ('BUY','SELL')),
  signal_candle_close_time bigint not null,
  accepted boolean not null,
  gate_id text not null,
  failed_conditions text[] not null default '{}',
  features jsonb,
  observed_at timestamptz not null default now(),
  unique (candidate_id, engine_version, base_config_version, repair_config_version)
);

create index if not exists amyfx_preview_scalper_telemetry_driver_time_idx
  on public.amyfx_preview_scalper_candidate_telemetry (driver_id, timeframe, signal_candle_close_time desc);
create index if not exists amyfx_preview_scalper_telemetry_rejected_idx
  on public.amyfx_preview_scalper_candidate_telemetry (gate_id, signal_candle_close_time desc)
  where accepted = false;

alter table public.amyfx_preview_scalper_pattern_configs enable row level security;
alter table public.amyfx_preview_scalper_candidate_telemetry enable row level security;

revoke all on public.amyfx_preview_scalper_pattern_configs from anon, authenticated;
revoke all on public.amyfx_preview_scalper_candidate_telemetry from anon, authenticated;

grant all on public.amyfx_preview_scalper_pattern_configs to service_role;
grant all on public.amyfx_preview_scalper_candidate_telemetry to service_role;
grant usage, select on all sequences in schema public to service_role;
