-- Amy FX Preview only: BT6/BT6.1 pattern engine, AMD driver, telemetry, and single-path news delivery.

alter table public.amyfx_preview_scalper_setups drop constraint if exists amyfx_preview_scalper_setups_model_check;
alter table public.amyfx_preview_scalper_setups
  add constraint amyfx_preview_scalper_setups_model_check check (model in (
    'IFVG_SCALPER','FVG_BUY_HIGH_QUALITY',
    'FVG','CRT','ORDER_BLOCK','BREAKER_BLOCK','RETEST_BOS',
    'TRENDLINE_BREAK_RETEST','EMA_PULLBACK','FALSE_BREAKOUT','RANGE_EXPANSION','AMD'
  ));

create table if not exists public.amyfx_preview_scalper_pattern_configs (
  config_type text not null check (config_type in ('BASE','REPAIR','AMD')),
  version text not null,
  enabled boolean not null default true,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  primary key (config_type, version)
);

insert into public.amyfx_preview_scalper_pattern_configs (config_type, version, enabled, payload)
values
  ('BASE', 'BT6-2025-V1', true, '{"scope":"nine_existing_drivers","entry":"raw_detector_unchanged","tp1_points":10,"tp2_points":20,"break_even":false,"max_hold_hours":24,"same_candle_rule":"SL_FIRST"}'::jsonb),
  ('REPAIR', 'BT6.1-2026-H1-V1', true, '{"drivers":["ORDER_BLOCK","RETEST_BOS","EMA_PULLBACK","BREAKER_BLOCK"],"operation":"base_gate_and_repair_overlay"}'::jsonb),
  ('AMD', 'AMD-2025-V1', true, '{"timeframes":["M30","H1"],"entry":"FVG_MIDPOINT_LIMIT","risk_points_min":10,"risk_points_max":30,"stop_cap_points":50}'::jsonb)
on conflict (config_type, version) do nothing;

create table if not exists public.amyfx_preview_scalper_candidate_telemetry (
  id bigint generated by default as identity primary key,
  candidate_id text not null,
  engine_version text not null,
  base_config_version text not null,
  repair_config_version text not null,
  driver_id text not null,
  timeframe text not null check (timeframe in ('M15','M30','H1','H4')),
  direction text not null check (direction in ('BUY','SELL')),
  signal_candle_close_time bigint not null,
  accepted boolean not null,
  gate_id text not null,
  failed_conditions text[] not null default '{}',
  features jsonb,
  observed_at timestamptz not null default now(),
  unique (candidate_id, engine_version, base_config_version, repair_config_version)
);

create index if not exists amyfx_preview_scalper_telemetry_driver_time_idx
  on public.amyfx_preview_scalper_candidate_telemetry (driver_id, timeframe, signal_candle_close_time desc);
create index if not exists amyfx_preview_scalper_telemetry_rejected_idx
  on public.amyfx_preview_scalper_candidate_telemetry (gate_id, signal_candle_close_time desc)
  where accepted = false;

create table if not exists public.amyfx_preview_news_delivery_ledger (
  id bigint generated by default as identity primary key,
  event_key text not null,
  news_id bigint not null references public.news(id) on delete cascade,
  stage text not null,
  recipient_scope text not null,
  device_token_id uuid references public.device_tokens(id) on delete cascade,
  idempotency_key text not null unique,
  status text not null default 'PENDING' check (status in ('PENDING','CLAIMED','SENT','RETRY','FAILED')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  claim_token uuid,
  claimed_at timestamptz,
  next_retry_at timestamptz,
  provider_message_id text,
  error text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (event_key, stage, recipient_scope)
);

create index if not exists amyfx_preview_news_ledger_claim_idx
  on public.amyfx_preview_news_delivery_ledger (status, next_retry_at, claimed_at)
  where status in ('PENDING','CLAIMED','RETRY');
create index if not exists amyfx_preview_news_ledger_device_idx
  on public.amyfx_preview_news_delivery_ledger (device_token_id, created_at desc);

create table if not exists public.amyfx_preview_scheduler_leases (
  lease_key text primary key,
  lease_token uuid not null,
  claimed_at timestamptz not null,
  expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);

create or replace function public.amyfx_claim_preview_news_delivery(
  p_event_key text,
  p_news_id bigint,
  p_stage text,
  p_recipient_scope text,
  p_device_token_id uuid,
  p_lease_seconds integer default 120
)
returns table (id bigint, claim_token uuid, idempotency_key text, attempt_count integer)
language plpgsql
security invoker
set search_path = public
as $$
declare
  claimed public.amyfx_preview_news_delivery_ledger%rowtype;
begin
  insert into public.amyfx_preview_news_delivery_ledger (
    event_key, news_id, stage, recipient_scope, device_token_id, idempotency_key
  ) values (
    p_event_key,
    p_news_id,
    p_stage,
    p_recipient_scope,
    p_device_token_id,
    'news:' || p_event_key || ':' || p_stage || ':' || p_recipient_scope
  )
  on conflict (event_key, stage, recipient_scope) do nothing;

  update public.amyfx_preview_news_delivery_ledger as ledger
  set
    status = 'CLAIMED',
    claim_token = gen_random_uuid(),
    claimed_at = now(),
    attempt_count = ledger.attempt_count + 1,
    updated_at = now(),
    error = null
  where ledger.event_key = p_event_key
    and ledger.stage = p_stage
    and ledger.recipient_scope = p_recipient_scope
    and (
      ledger.status = 'PENDING'
      or (ledger.status = 'RETRY' and coalesce(ledger.next_retry_at, now()) <= now())
      or (ledger.status = 'CLAIMED' and ledger.claimed_at < now() - make_interval(secs => greatest(30, p_lease_seconds)))
    )
  returning ledger.* into claimed;

  if claimed.id is not null then
    return query select claimed.id, claimed.claim_token, claimed.idempotency_key, claimed.attempt_count;
  end if;
end;
$$;

create or replace function public.amyfx_complete_preview_news_delivery(
  p_id bigint,
  p_claim_token uuid,
  p_status text,
  p_provider_message_id text default null,
  p_error text default null,
  p_retry_after_seconds integer default 120
)
returns boolean
language plpgsql
security invoker
set search_path = public
as $$
declare
  changed bigint;
begin
  if p_status not in ('SENT','RETRY','FAILED') then
    raise exception 'invalid delivery status';
  end if;
  update public.amyfx_preview_news_delivery_ledger
  set
    status = p_status,
    provider_message_id = p_provider_message_id,
    error = left(p_error, 1800),
    sent_at = case when p_status = 'SENT' then now() else sent_at end,
    next_retry_at = case when p_status = 'RETRY' then now() + make_interval(secs => greatest(30, p_retry_after_seconds)) else null end,
    claim_token = null,
    updated_at = now()
  where id = p_id and status = 'CLAIMED' and claim_token = p_claim_token;
  get diagnostics changed = row_count;
  return changed = 1;
end;
$$;

create or replace function public.amyfx_claim_preview_scheduler_lease(
  p_lease_key text,
  p_lease_seconds integer default 90
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare
  token uuid := gen_random_uuid();
  claimed uuid;
begin
  insert into public.amyfx_preview_scheduler_leases (lease_key, lease_token, claimed_at, expires_at, updated_at)
  values (p_lease_key, token, now(), now() + make_interval(secs => greatest(30, p_lease_seconds)), now())
  on conflict (lease_key) do update
  set lease_token = excluded.lease_token,
      claimed_at = excluded.claimed_at,
      expires_at = excluded.expires_at,
      updated_at = excluded.updated_at
  where public.amyfx_preview_scheduler_leases.expires_at <= now()
  returning lease_token into claimed;
  return claimed;
end;
$$;

create or replace function public.amyfx_release_preview_scheduler_lease(
  p_lease_key text,
  p_lease_token uuid
)
returns boolean
language plpgsql
security invoker
set search_path = public
as $$
declare
  changed bigint;
begin
  delete from public.amyfx_preview_scheduler_leases
  where lease_key = p_lease_key and lease_token = p_lease_token;
  get diagnostics changed = row_count;
  return changed = 1;
end;
$$;

alter table public.amyfx_preview_scalper_pattern_configs enable row level security;
alter table public.amyfx_preview_scalper_candidate_telemetry enable row level security;
alter table public.amyfx_preview_news_delivery_ledger enable row level security;
alter table public.amyfx_preview_scheduler_leases enable row level security;

revoke all on public.amyfx_preview_scalper_pattern_configs from anon, authenticated;
revoke all on public.amyfx_preview_scalper_candidate_telemetry from anon, authenticated;
revoke all on public.amyfx_preview_news_delivery_ledger from anon, authenticated;
revoke all on public.amyfx_preview_scheduler_leases from anon, authenticated;
revoke all on function public.amyfx_claim_preview_news_delivery(text,bigint,text,text,uuid,integer) from public, anon, authenticated;
revoke all on function public.amyfx_complete_preview_news_delivery(bigint,uuid,text,text,text,integer) from public, anon, authenticated;
revoke all on function public.amyfx_claim_preview_scheduler_lease(text,integer) from public, anon, authenticated;
revoke all on function public.amyfx_release_preview_scheduler_lease(text,uuid) from public, anon, authenticated;

grant all on public.amyfx_preview_scalper_pattern_configs to service_role;
grant all on public.amyfx_preview_scalper_candidate_telemetry to service_role;
grant all on public.amyfx_preview_news_delivery_ledger to service_role;
grant all on public.amyfx_preview_scheduler_leases to service_role;
grant execute on function public.amyfx_claim_preview_news_delivery(text,bigint,text,text,uuid,integer) to service_role;
grant execute on function public.amyfx_complete_preview_news_delivery(bigint,uuid,text,text,text,integer) to service_role;
grant execute on function public.amyfx_claim_preview_scheduler_lease(text,integer) to service_role;
grant execute on function public.amyfx_release_preview_scheduler_lease(text,uuid) to service_role;
grant usage, select on all sequences in schema public to service_role;
