create table if not exists public.amyfx_preview_scalper_setups (
  id text primary key,
  engine_version text not null,
  model text not null check (model in ('IFVG_SCALPER', 'FVG_BUY_HIGH_QUALITY')),
  symbol text not null default 'XAU/USD' check (symbol = 'XAU/USD'),
  direction text not null check (direction in ('BUY', 'SELL')),
  status text not null check (status in ('WAITING_NEXT_OPEN','ACTIVE','BE_ACTIVE','TP_HIT','SL_HIT','BE_HIT','TIME_EXIT','INVALIDATED','CANCELLED')),
  recommendation_status text not null default 'PENDING' check (recommendation_status in ('PENDING','VALID','RISK_LIMIT','DUPLICATE_CLUSTER','INVALID','CLOSED')),
  signal_candle_open_time bigint not null,
  signal_candle_close_time bigint not null,
  entry_candle_open_time bigint,
  entry_price double precision,
  initial_stop_loss double precision,
  stop_loss double precision,
  break_even_trigger double precision,
  target_price double precision,
  risk double precision,
  buffer_atr double precision not null,
  max_bars integer not null default 4 check (max_bars between 1 and 16),
  bars_elapsed integer not null default 0 check (bars_elapsed >= 0),
  last_evaluated_open_time bigint,
  htf_bias text not null check (htf_bias in ('BULLISH', 'BEARISH')),
  htf_candle_close_time bigint,
  zone_bottom double precision not null,
  zone_top double precision not null,
  source_fvg_id text not null,
  stop_reference double precision not null,
  atr_at_signal double precision not null,
  be_armed boolean not null default false,
  result_r double precision,
  exit_price double precision,
  exit_time bigint,
  quality jsonb not null default '{}'::jsonb,
  priority integer not null default 99,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (zone_top > zone_bottom),
  check (atr_at_signal > 0)
);
create index if not exists amyfx_preview_scalper_setups_active_idx on public.amyfx_preview_scalper_setups (status, priority, signal_candle_close_time desc);
create index if not exists amyfx_preview_scalper_setups_recent_idx on public.amyfx_preview_scalper_setups (signal_candle_close_time desc);

create table if not exists public.amyfx_preview_scalper_events (
  id bigint generated by default as identity primary key,
  setup_id text not null references public.amyfx_preview_scalper_setups(id) on delete cascade,
  status text not null,
  event_time timestamptz not null default now(),
  candle_time bigint,
  price double precision,
  result_r double precision,
  message text not null,
  notification_eligible boolean not null default true,
  notified_at timestamptz,
  payload jsonb not null default '{}'::jsonb,
  unique (setup_id, status)
);
create index if not exists amyfx_preview_scalper_events_pending_idx on public.amyfx_preview_scalper_events (notification_eligible, notified_at, event_time) where notification_eligible = true and notified_at is null;

create table if not exists public.amyfx_preview_scalper_notification_logs (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.amyfx_preview_scalper_events(id) on delete cascade,
  device_token_id uuid not null references public.device_tokens(id) on delete cascade,
  status text not null check (status in ('sent','failed')),
  provider_message_id text,
  error text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (event_id, device_token_id)
);

create table if not exists public.amyfx_preview_scalper_runs (
  run_bucket bigint primary key,
  status text not null default 'RUNNING' check (status in ('RUNNING','COMPLETED','FAILED')),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  result jsonb not null default '{}'::jsonb,
  error text
);

alter table public.amyfx_preview_scalper_setups enable row level security;
alter table public.amyfx_preview_scalper_events enable row level security;
alter table public.amyfx_preview_scalper_notification_logs enable row level security;
alter table public.amyfx_preview_scalper_runs enable row level security;
revoke all on public.amyfx_preview_scalper_setups from anon, authenticated;
revoke all on public.amyfx_preview_scalper_events from anon, authenticated;
revoke all on public.amyfx_preview_scalper_notification_logs from anon, authenticated;
revoke all on public.amyfx_preview_scalper_runs from anon, authenticated;
grant all on public.amyfx_preview_scalper_setups to service_role;
grant all on public.amyfx_preview_scalper_events to service_role;
grant all on public.amyfx_preview_scalper_notification_logs to service_role;
grant all on public.amyfx_preview_scalper_runs to service_role;
grant usage, select on all sequences in schema public to service_role;

do $$
declare existing_job_id bigint;
begin
  select jobid into existing_job_id from cron.job where jobname = 'amyfx-preview-scalper-engine' limit 1;
  if existing_job_id is not null then perform cron.unschedule(existing_job_id); end if;
  perform cron.schedule(
    'amyfx-preview-scalper-engine',
    '* * * * *',
    $cron$select net.http_post(
      url := 'https://wliecyxzlwhmtftnfnps.supabase.co/functions/v1/scalper-engine',
      headers := '{"Content-Type":"application/json"}'::jsonb,
      body := '{}'::jsonb,
      timeout_milliseconds := 55000
    );$cron$
  );
end $$;
