name: JavaScript Regression

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Run Mapping regression tests
        run: |
          node --version
          node --test --test-reporter=spec tests/*.test.mjs
